// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/15/2025, 5:18:02 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/paymei/Documents/Development/github/dubaifw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/plugins/**/*.{js,ts,mjs}","/Users/paymei/Documents/Development/github/dubaifw/composables/**/*.{js,ts,mjs}","/Users/paymei/Documents/Development/github/dubaifw/utils/**/*.{js,ts,mjs}","/Users/paymei/Documents/Development/github/dubaifw/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/dubaifw/app.config.{js,ts,mjs}","/Users/paymei/Documents/Development/github/dubaifw/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;